### ISSUE TITLE
How does yodaqa differs from Solr for example ?

### ISSUE THREAD

**Issue by peterps-health** [brmson/yodaqa#10]
Hi,

Looks very interesting, coming from the healthcare area, thought of using it. Currently for QA system we use Solr how yodaqa is better ?

Thanks,
Peter

**Comment by pasky** [comment]
Hi!
Solr is an information retrieval system that can retrieve documents based on keywords.  YodaQA actually uses Solr under the hood, but (i) it can understand naturally phrased questions, and (ii) it does not return whole documents (or snippets around keywords), but aims to return just specific answers for the questions.

**Comment by peterps-health** [comment]
Hi,
Thank you for your reply,
That's definitely interesting,
(i) it can understand naturally phrased questions - e.g. tokens created as input for Solr are being formed based on user query(e.g. can be transformed/change or reduced at this stage)
(ii) specific answers this is uber cool, since you must be very well aware of this solution ;) could you please point me to areas that could allow me to tailor answers for a particular domain ? (e.g. introduce context to healthcare to make application more ;smart;)

Thanks,
Peter

**Comment by pasky** [comment]
Hi!
Yes, (i) is possible; https://github.com/tamingtext/book has some examples in this.
Regarding (ii), of course the system is very far from perfect; I guess you already played around with the live version a bit? To explain in more detail, it'd be good if you read on YodaQA's architecture a bit. As another example, take a look at the branch f/bioasq-geneontology - it contains a custom knowledge base (GeneOntology) added as an extra source of knowledge for answer verification. You could also add a PubMed search in addition to full-text search on Wikipedia, etc.
