### ISSUE TITLE
what's the plan for integrating SINA?

### ISSUE THREAD

**Issue by daqulazhang** [brmson/yodaqa#13]
Hi, I read the yodaqa menu, it says there's plan for integrating sina, I am wondering how it's going now and is there detailed schedule for it?

**Comment by pasky** [comment]
Hi! I'm not sure what do you mean by SINA, care to explain?

  Right now, we are focusing on improving movies performance (and, by
extension, performance of general QA on top of structured databases).
We are now trying to put the operational details on the wiki, you can
find it in the "subtasks" section.

  We don't have a specific schedule, but we are working as fast as
possible. :)  Let me know if you're particularly interested to use
YodaQA for something specific, or would like to contribute something.

**Comment by jbauer180266** [comment]
I think he meant http://sina.aksw.org/ over at openQA, also mentioned in their Showcase http://openqa.aksw.org/showcases.xhtml [no warranty for external links] and I think the answer is that the Brmson platform has not too much to do with openQA anymore, so there are likely no integration plans at this point.

**Comment by pasky** [comment]
Oh, interesting! (Though it didn't reply to my question for a couple of minutes...)

To further clarify, the platform had never anything to do with openqa.aksw.org, which is a separate initiative. Historically, we have been experimenting with OAQA, which used "openqa" as a synonym at a couple of places (when there was no openqa.aksw.org yet). Confusing!
