### ISSUE TITLE
[SOLVED] YodaQA web interface seems to get stuck on Ubuntu 14.04

### ISSUE THREAD

**Issue by jbauer180266** [brmson/yodaqa#16]
I have trouble getting answers on Ubuntu 14.04 with both YodaQA release 1.2 and the current Github head. I'm on a Lenovo Thinkpad W520 with 8GB of RAM and a Quadro K1000M. I use Firefox 41.0 with NoScript (all scripts on localhost allowed!).

"gradlew --info check" ran fine. The demo on http://live.ailao.eu/ works fine for me. The command line version works fine and presents a list of 24 answer candidates with confidence scores, the first one of which is correct.

But:
# echo | ./gradlew -Dorg.gradle.java.home=/usr/lib/jvm/java-7-openjdk-amd64/ -Dorg.slf4j.simpleLogger.log.cz.brmlab.yodaqa=debug web -q seems to get stuck after asking a question

[I had to shorten the log quite a bit for Github, but sent the full log to Petr via mail]
DEBUG LATByWordnet - expanded LAT sacred text/6441260 to wn LATs:  | writing/6374360:-1.0 | written communication/6360590:-2.0 | communication/33319:-3.0
DEBUG LATByNE - .. LAT organization/8024893 by NE Tor Books
DEBUG LATMatchTyCor - .. TyCor hit person-publisher match person/7846 sp. -3.0 (q 0.0, a -3.0)
DEBUG LATMatchTyCor - q-hit LAT match for <<Tor Books>>
DEBUG LATMatchTyCor - .. TyCor best person-publisher match person/7846 sp. -3.0 (q 0.0, a -3.0)
DEBUG FocusGenerator - .. Focus '0-312-93208-1' in: 0-312-93208-1
DEBUG LATMatchTyCor - multi-hit LAT match for <<Tor Books>>
DEBUG AnswerCASMerger - in: canAnswer Tor Books, isLast 6 < 7, cases 307 < 307
DEBUG FocusGenerator - .. Focus 'Speaker' in: Speaker for the Dead
INFO LATByWordnet - ?! word isbn of POS NNS not in Wordnet
DEBUG AnswerCASMerger - in: canAnswer 0-312-93208-1, isLast 6 < 7, cases 308 < 308
DEBUG LATNormalize - .. LAT <<number of pages>> copied to <<number>>
INFO LATByWordnet - ?! word number of pages of POS NNS not in Wordnet
DEBUG LATByWordnet - expanded LAT number to wn LATs:  | amount/5115065:-1.0 | magnitude/5097645:-2.0 | property/4923519:-3.0 | attribute/24444:-4.0 | definite quantity/13597304:-1.0 | measure/33914:-2.0 | performance/6904543:-1.0 | show/6631572:-2.0 | social event/7303344:-3.0 | event/29677:-4.0 | signal/6804229:-1.0 | communication/33319:-2.0 | symbol/6819327:-1.0 | periodical/6605500:-1.0 | publication/6601855:-2.0 | work/4606723:-3.0 | product/4014270:-4.0 | creation/3133774:-5.0 | artifact/22119:-6.0 | company/8201779:-1.0 | social gathering/8269132:-2.0 | gathering/7991473:-3.0 | social group/7967506:-4.0 | group/31563:-5.0 | positive identification/6898439:-1.0 | identification/6898133:-2.0 | evidence/6656171:-3.0 | indication/6810027:-4.0 | size/5102953:-1.0 | item/3593583:-1.0 | whole/3553:-2.0 | grammatical category/6320373:-1.0 | class/8014145:-2.0 | collection/7968050:-3.0 | merchandise/3754377:-1.0 | commodity/3080712:-2.0
DEBUG LATByQuantity - .. Quantity CD LAT measure/33914, magnitude relation/13837364, magnitude/5097645 based on [NN] <<384>>
DEBUG LATMatchTyCor - failed TyCor for <<384>>
DEBUG AnswerCASMerger - in: canAnswer 384, isLast 6 < 7, cases 309 < 309
DEBUG LATNormalize - .. LAT <<subsequent work>> copied to <<work>>
INFO LATByWordnet - ?! word subsequent work of POS NNS not in Wordnet
DEBUG LATByWordnet - expanded LAT work to wn LATs:  | activity/408356:-1.0 | act/30657:-2.0 | product/4014270:-1.0 | creation/3133774:-2.0 | artifact/22119:-3.0 | occupation/583425:-1.0 | learning/5760541:-1.0 | basic cognitive process/5709891:-2.0 | process/5709328:-3.0 | energy/11472635:-1.0 | physical phenomenon/11439518:-2.0 | natural phenomenon/11428673:-3.0 | phenomenon/34512:-4.0 | geographic point/8596234:-1.0 | point/8637636:-2.0 | location/27365:-3.0 | end product/3292089:-1.0
DEBUG LATMatchTyCor - failed TyCor for <<Speaker for the Dead>>
DEBUG AnswerCASMerger - in: canAnswer Speaker for the Dead, isLast 7 < 7, cases 310 < 310
DEBUG AnswerCASMerger - hitlist merge the Dead|the Dead
DEBUG AnswerCASMerger - hitlist merge science fiction books by Orson Scott Card|science fiction books by Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge 2004|2004
DEBUG AnswerCASMerger - hitlist merge 2004|2004
DEBUG AnswerCASMerger - hitlist merge 2013|2013
DEBUG AnswerCASMerger - hitlist merge a 2013 American science fiction action film|a 2013 American science fiction action film
DEBUG AnswerCASMerger - hitlist merge American author Orson Scott Card|American author Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge 1986|1986
DEBUG AnswerCASMerger - hitlist merge 1985|1985
DEBUG AnswerCASMerger - hitlist merge 1985|1985
DEBUG AnswerCASMerger - hitlist merge 1985|1985
DEBUG AnswerCASMerger - hitlist merge 1985|1985
DEBUG AnswerCASMerger - hitlist merge 1985|1985
DEBUG AnswerCASMerger - hitlist merge English Language|English Language
DEBUG AnswerCASMerger - hitlist merge English Language|English Language
DEBUG AnswerCASMerger - hitlist merge The "Ender's Game" series (often referred to as the Enderverse or the "Ender" saga)|The "Ender's Game" series (often referred to as the Enderverse or the "Ender" saga)
DEBUG AnswerCASMerger - hitlist merge the "Ender" saga|the "Ender" saga
DEBUG AnswerCASMerger - hitlist merge the Enderverse|the Enderverse
DEBUG AnswerCASMerger - hitlist merge 22909973|22909973
DEBUG AnswerCASMerger - hitlist merge Speaker for the Dead|Speaker for the Dead
DEBUG AnswerCASMerger - hitlist merge Speaker for the Dead|Speaker for the Dead
DEBUG AnswerCASMerger - hitlist merge Speaker for the Dead|Speaker for the Dead
DEBUG AnswerCASMerger - hitlist merge Written Work|Written Work
DEBUG AnswerCASMerger - hitlist merge Jane|Jane
DEBUG AnswerCASMerger - hitlist merge Jane|Jane
DEBUG AnswerCASMerger - hitlist merge Ender Wiggin|Ender Wiggin
DEBUG AnswerCASMerger - hitlist merge the Ender's|the Ender's
DEBUG AnswerCASMerger - hitlist merge a series of science fiction books by Orson Scott Card|a series of science fiction books by Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Adaptation|Adaptation
DEBUG AnswerCASMerger - hitlist merge the novel of the same name by Orson Scott Card|the novel of the same name by Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge a 1985 military science fiction novel by American author Orson Scott Card|a 1985 military science fiction novel by American author Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card|Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Ender|Ender
DEBUG AnswerCASMerger - hitlist merge the novel|the novel
DEBUG AnswerCASMerger - hitlist merge the novel|the novel
DEBUG AnswerCASMerger - hitlist merge Work of Fiction|Work of Fiction
DEBUG AnswerCASMerger - hitlist merge the same name|the same name
DEBUG AnswerCASMerger - hitlist merge a 1985 military science fiction|a 1985 military science fiction
DEBUG AnswerCASMerger - hitlist merge the same name by Orson Scott Card|the same name by Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge Ender's|Ender's
DEBUG AnswerCASMerger - hitlist merge United States|United States
DEBUG AnswerCASMerger - hitlist merge Book|Book
DEBUG AnswerCASMerger - hitlist merge Orson Scott Card.|Orson Scott Card.
DEBUG AnswerCASMerger - hitlist merge Adapted Work|Adapted Work
DEBUG AnswerCASMerger - hitlist merge Award-Nominated Work|Award-Nominated Work
DEBUG AnswerCASMerger - hitlist merge Science fiction|Science fiction
DEBUG AnswerCASMerger - hitlist merge 384|384
DEBUG AnswerCASMerger - hitlist merge a series|a series
DEBUG AnswerCASMerger - hitlist merge a series|a series
DEBUG AnswerCASMerger - hitlist merge Award-Winning Work|Award-Winning Work
DEBUG AnswerCASMerger - hitlist merge Tor Books|Tor Books
DEBUG AnswerCASMerger - hitlist merge English language|English language
DEBUG AnswerCASMerger - hitlist merge the Enderverse or the "Ender" saga|the Enderverse or the "Ender" saga
DEBUG AnswerCASMerger - hitlist merge characters|characters
DEBUG AnswerCASMerger - hitlist merge The "Ender's Game" series|The "Ender's Game" series
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge Ender's Game|Ender's Game
DEBUG AnswerCASMerger - hitlist merge the Ender's Game series|the Ender's Game series
DEBUG AnswerCASMerger - hitlist merge a 2013 American science fiction action film based on the novel of the same name by Orson Scott Card|a 2013 American science fiction action film based on the novel of the same name by Orson Scott Card
DEBUG AnswerCASMerger - hitlist merge Speaker|Speaker
DEBUG AnswerCASMerger - hitlist merge Speaker|Speaker
DEBUG AnswerCASMerger - hitlist merge Card|Card
DEBUG AnswerCASMerger - hitlist merge Card|Card
DEBUG AnswerCASMerger - hitlist merge Card|Card
DEBUG AnswerCASMerger - hitlist merge Card|Card
DEBUG AnswerCASMerger - hitlist merge science fiction books|science fiction books
DEBUG AnswerScoreDecisionForest - scoring with model AnswerScoreDecisionForest.model
DEBUG AnswerGSHook - ------------------------------------------------
DEBUG AnswerCASMerger - in: canAnswer Orson Scott Card., isLast 0 < 1, cases 1 < 0
DEBUG AnswerCASMerger - in: canAnswer Orson Scott Card, isLast 0 < 1, cases 2 < 0
DEBUG AnswerCASMerger - in: canAnswer American author Orson Scott Card, isLast 0 < 1, cases 3 < 0
DEBUG AnswerCASMerger - in: canAnswer a partial list of characters in the Ender's Game series, isLast 0 < 1, cases 4 < 0
DEBUG AnswerCASMerger - in: canAnswer Card, isLast 0 < 1, cases 5 < 0
DEBUG AnswerCASMerger - in: canAnswer Jane, isLast 0 < 1, cases 6 < 0
DEBUG AnswerCASMerger - in: canAnswer Ender Wiggin, isLast 0 < 1, cases 7 < 0
DEBUG AnswerCASMerger - in: canAnswer Neal Shusterman, isLast 0 < 1, cases 8 < 0
DEBUG AnswerCASMerger - in: canAnswer many opportunities through the 1980s and 1990s to sell the rights of "Ender's Game" to Hollywood studios, isLast 0 < 1, cases 9 < 0
DEBUG AnswerCASMerger - in: canAnswer John Harris, isLast 0 < 1, cases 10 < 0
DEBUG AnswerCASMerger - in: canAnswer Orson Scott Card's, isLast 0 < 1, cases 11 < 0
DEBUG AnswerCASMerger - in: canAnswer the Ender's Game series, isLast 0 < 1, cases 12 < 0
DEBUG AnswerCASMerger - in: canAnswer The "Ender's Game" series (often referred to as the Enderverse or the "Ender" saga), isLast 0 < 1, cases 13 < 0
DEBUG AnswerCASMerger - in: canAnswer Elisabeth Hirsch, isLast 0 < 1, cases 14 < 0
DEBUG AnswerCASMerger - in: canAnswer characters, isLast 0 < 1, cases 15 < 0
DEBUG AnswerCASMerger - in: canAnswer List of Ender's Game series planets, isLast 0 < 1, cases 16 < 0
DEBUG AnswerCASMerger - in: canAnswer Elaborating, isLast 0 < 1, cases 17 < 0
DEBUG AnswerCASMerger - in: canAnswer a 1985 military science fiction, isLast 0 < 1, cases 18 < 0
DEBUG AnswerCASMerger - in: canAnswer a 1985 military science fiction novel by American author Orson Scott Card, isLast 0 < 1, cases 19 < 0
DEBUG AnswerCASMerger - in: canAnswer Christopher Yost, isLast 0 < 1, cases 20 < 0
DEBUG AnswerCASMerger - in: canAnswer Steve Jablonsky, isLast 0 < 1, cases 21 < 0
DEBUG AnswerCASMerger - in: canAnswer Tor Books, isLast 0 < 1, cases 22 < 0
DEBUG AnswerCASMerger - in: canAnswer Valentine, isLast 0 < 1, cases 23 < 0
DEBUG AnswerCASMerger - in: canAnswer the novel, isLast 0 < 1, cases 24 < 0
DEBUG AnswerCASMerger - in: canAnswer Hailee Steinfeld, isLast 0 < 1, cases 25 < 0
DEBUG AnswerCASMerger - in: canAnswer Print, isLast 1 < 1, cases 26 < 26
DEBUG AnswerTextMerger - subsumed <<Orson Scott Card>>:0.9301081628019869 < <<Orson Scott Card.>>
WARN AnswerTextMerger - .. losing DBpPropertyLAT <<author>>
WARN AnswerTextMerger - .. losing DBpOntologyLAT <<author>>
WARN AnswerTextMerger - .. losing FBOntologyLAT <<author>>
WARN AnswerTextMerger - .. losing FBOntologyLAT <<nominee>>
WARN AnswerTextMerger - .. losing FBOntologyLAT <<award nominations: award nominee>>
DEBUG AnswerTextMerger - subsumed <<Orson Scott Card's>>:0.7087671384630194 < <<Orson Scott Card.>>
DEBUG AnswerScoreDecisionForest - scoring with model AnswerScoreDecisionForest1.model
DEBUG AnswerGSHook - ------------------------------------------------
DEBUG AnswerCASMerger - in: canAnswer American author Orson Scott Card, isLast 0 < 1, cases 2 < 0
DEBUG AnswerCASMerger - in: canAnswer Card, isLast 0 < 1, cases 3 < 0
DEBUG AnswerCASMerger - in: canAnswer Orson Scott Card., isLast 0 < 1, cases 4 < 0
DEBUG AnswerCASMerger - in: canAnswer Jane, isLast 0 < 1, cases 5 < 0
DEBUG AnswerCASMerger - in: canAnswer Ender Wiggin, isLast 1 < 1, cases 6 < 6
DEBUG AnswerScoreDecisionForest - scoring with model AnswerScoreDecisionForest2.model
DEBUG AnswerGSHook - ------------------------------------------------

And then nothing seems to happen anymore [waited for at least 3 minutes]. Web interface went to http://localhost:4567/q and only reads {"id":"237100379"} or {"id":"746060982"} or similar.

Unrelated notes: YodaQA does not compile with Java 8 on my system (probably known). Without -Dorg.slf4j.simpleLogger.log.cz.brmlab.yodaqa=debug the CLI goes straight back to shell.

**Comment by pasky** [comment]
Hi! Any particular reason you use the ``echo |`` when starting the web interface?

Can you please explain more thoroughly what happens in the web interface? Did the answer appear in the list of "in progress" answers after submitting it? Does it get stuck there, or not appear at all? If you click on it, do you get the progress bar or something else? Could you elaborate "Web interface went to http://localhost:4567/q" - did you get some redirect to that URL? The replies you are getting (these appear in your browser window as plaintext?) seem indicative of POST requests to http://localhost:4567/q, not GET requests (these should get HTTP errors), which is really confusing, are you pushing the [Submit] button while waiting for the answer?

I never tried building with Java8 since it's not in Debian by default. If you are interested in getting it to work, I'll be happy to take patches! (But it's a matter for another issue I guess.)

**Comment by jbauer180266** [comment]
Solved. It just occured to me: Never make assumptions. I might have allowed all scripts in NoScript, but that doesn't mean it won't interfere with anything. It's a bit strange that the demo works and localhost doesn't with allowed scripts, but when I launch Firefox in safe mode everything works fine.

Sorry - should have checked that sooner.

PS:
And of course you're right about "echo |" - it can be left out.

**Comment by pasky** [comment]
Great that we've solved this then. :-)
