### ISSUE TITLE
I ran the wikipedia extractor and it stopped at folder IF. Did I do something wrong?

### ISSUE THREAD

**Issue by simonhughes22** [brmson/yodaqa#18]
Awesome project btw. I didn't get any errors but the extractor stopped at directory IF. Should it go to ZZ?

**Comment by pasky** [comment]
I think that's normal, the number of folders corresponds to size of the
wiki corpus.

**Comment by simonhughes22** [comment]
Ah ok thanks. I thought it was something to do with the topics. Markups comes back very clean. We've been struggling with parsing that, and I don't want to hand roll my own so thanks for sharing.

**Comment by pasky** [comment]
Glad it helps :)
