### ISSUE TITLE
Is demo broken?

### ISSUE THREAD

**Issue by MartyIX** [brmson/yodaqa#44]
Hi,

when I open http://live.ailao.eu/ I can see in my Google Chrome dev console that `cordova.js` cannot be downloaded.

Regards,
Martin

PS: I have tried Yoda before and it looks like a really cool project. Good work!

**Comment by pasky** [comment]
Oh my, Java doesn't cease to surprise:

    java.lang.OutOfMemoryError: GC overhead limit exceeded

For the time being, I'm just restarting it.  The Cordova error is harmless.  Thanks for the headsup!
