### ISSUE TITLE
freebase.ailao.eu is down?

### ISSUE THREAD

**Issue by satyagadepalli** [brmson/yodaqa#56]
[ec2-user@ip-........... hub]$ telnet freebase.ailao.eu 3030
Trying 147.32.85.33...
telnet: connect to address 147.32.85.33: No route to host
Trying 2001:718:2:1638:801f:a7ff:fe97:83ed...
telnet: connect to address 2001:........: Network is unreachable

Is the free base service down?

thanx

**Comment by pasky** [comment]
Yes, sorry for the trouble, we had a power outage and resulting HW equipment failure.  It may take up to a day or two to fix this, @pichljan is working on it.

**Comment by satyagadepalli** [comment]
Thanks for the quick reply. Please let us know once it is back and running.

Regards

**Comment by pasky** [comment]
Fix.ed
