### ISSUE TITLE
How to add more fulltext sources

### ISSUE THREAD

**Issue by xteejx** [brmson/yodaqa#62]
This software is simply astounding. 

I'd love to know, as would many, exactly how to add multiple sources of information. 
Ideally by adding more documents to solr for indexing, such as other Wikis, Project Gutenberg texts, etc. I assume these would all be processed with the fulltext search using solr whether there is a dbpedia clue or not?

Please help.

**Comment by pasky** [comment]
Documenting this is a subject of #17 but it is not possible out of the box, only in principle. (The architecture allows it, but there is no explicit code support for querying multiple Solr indices.  Sure, you could just make sure IDs are non-duplicate and index everything in a single Solr collection, as a starting point...)

**Comment by xteejx** [comment]
Thanks for the reply. Will look at doing that, and maybe playing with the code to add multiple instances of solr (or multiple collections).

**Comment by pasky** [comment]
Any contributions to the code or just to the documentation will be
welcome!

**Comment by xteejx** [comment]
Will definitely be contributing code back if I come up with anything, just
getting up to speed with the code. Not used to java.

**Comment by xteejx** [comment]
Having looked at the code, I really don't think I'm going to be much use there, so instead will create a good dataset of questions sourced from many places, will curate this with question, answer, LAT type and anything else you feel necessary to help towards training the system.

**Comment by pasky** [comment]
That would be also really cool! :)

**Comment by xteejx** [comment]
Made a start on this last night, up to about 250 questions. There are a few inference based ones in there too but shouldn't be too hard to still find the answer using current system. Benchmarking using base YodaQA too with correct answer position number and confidence. Hopefully that extra info will go towards diagnosis, easily removable. :)
