### ISSUE TITLE
Question analysis fails

### ISSUE THREAD

**Issue by xteejx** [brmson/yodaqa#63]
IPv4 used, and no issues until yesterday. No local code changes, latest git.
Relevant debug output after NLP resources processed:

DEBUG FocusGenerator - ADVMOD+how known
DEBUG SVGenerator - SV: known
DEBUG LATByFocus - new LAT by Focus: <<known>>/0
DEBUG LATByFocus - new LAT by Focus: <<know>>/0
DEBUG LATByWordnet - checking noun synsets of know/596016
DEBUG LATByWordnet - .. adding LAT noun knowing
DEBUG LATByWordnet - expanded LAT know to wn LATs:  | knowing/5812801:0.0 | higher cognitive process/5778661:-1.0 | process/5709328:-2.0
INFO LATByWordnet - ?! word known of POS VBN not in Wordnet
DEBUG ClueByTokenConstituent - new by NP: gas Nitrous Oxide
DEBUG ClueByTokenConstituent - new by Token: gas
DEBUG ClueByTokenConstituent - new by Token: Nitrous
DEBUG ClueByTokenConstituent - new by Token: Oxide
DEBUG ClueByTokenConstituent - new by ADVP: better
DEBUG ClueByTokenConstituent - new by Token: better
DEBUG ClueBySV - new by SV: known
DEBUG ClueByLAT - new by WordnetLAT: knowing
DEBUG ClueByLAT - new by LAT: known
DEBUG ClueBySubject - new by Subject NP: the gas Nitrous Oxide
DEBUG ClueBySubject - new by Subject Token: Oxide
DEBUG CluesToConcepts - fuzzy-lookup(gas Nitrous Oxide) returned: d3.0 ~N2o nitrous oxide [N2O: Nitrous Oxide] N2O:_Nitrous_Oxide 0
ALERT: main seems stuck for more than 300s waiting for a job delivery.
Thread[main,5,main]  - Future java.util.concurrent.FutureTask@15a806a2 done false canc false :: AE cz.brmlab.yodaqa.analysis.question.QuestionAnalysisAE from CAS org.apache.uima.cas.impl.CASImpl@1efb1a38 (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@4ce1292a)

ALERT: pool-2-thread-1 seems stuck for more than 300s waiting for a job delivery.
Thread[pool-2-thread-1,5,main]  - Future java.util.concurrent.FutureTask@2bf9a35a done false canc false :: AE cz.brmlab.yodaqa.analysis.question.CluesToConcepts from CAS org.apache.uima.cas.impl.CASImpl@1efb1a38 (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@4341bc48)

ALERT: main seems stuck for more than 300s waiting for a job delivery.
Thread[main,5,main]  - Future java.util.concurrent.FutureTask@15a806a2 done false canc false :: AE cz.brmlab.yodaqa.analysis.question.QuestionAnalysisAE from CAS org.apache.uima.cas.impl.CASImpl@1efb1a38 (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@4ce1292a)

ALERT: pool-2-thread-1 seems stuck for more than 300s waiting for a job delivery.
Thread[pool-2-thread-1,5,main]  - Future java.util.concurrent.FutureTask@2bf9a35a done false canc false :: AE cz.brmlab.yodaqa.analysis.question.CluesToConcepts from CAS org.apache.uima.cas.impl.CASImpl@1efb1a38 (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@4341bc48)

**Comment by pasky** [comment]
Hi! Is there any error in the logs above what you pasted?  Normally,
CluesToConcepts should print an error on time out.  What does the command
ping6 dbp-labels.ailao.eu return?

> IPv4 used, and no issues until yesterday. No local code changes, latest git.
> Relevant debug output after NLP resources processed:
> 
> 
> DEBUG FocusGenerator - ADVMOD+how known
> DEBUG SVGenerator - SV: known
> DEBUG LATByFocus - new LAT by Focus: <<known>>/0
> DEBUG LATByFocus - new LAT by Focus: <<know>>/0
> DEBUG LATByWordnet - checking noun synsets of know/596016
> DEBUG LATByWordnet - .. adding LAT noun knowing
> DEBUG LATByWordnet - expanded LAT know to wn LATs:  | knowing/5812801:0.0 | higher cognitive process/5778661:-1.0 | process/5709328:-2.0
> INFO LATByWordnet - ?! word known of POS VBN not in Wordnet
> DEBUG ClueByTokenConstituent - new by NP: gas Nitrous Oxide
> DEBUG ClueByTokenConstituent - new by Token: gas
> DEBUG ClueByTokenConstituent - new by Token: Nitrous
> DEBUG ClueByTokenConstituent - new by Token: Oxide
> DEBUG ClueByTokenConstituent - new by ADVP: better
> DEBUG ClueByTokenConstituent - new by Token: better
> DEBUG ClueBySV - new by SV: known
> DEBUG ClueByLAT - new by WordnetLAT: knowing
> DEBUG ClueByLAT - new by LAT: known
> DEBUG ClueBySubject - new by Subject NP: the gas Nitrous Oxide
> DEBUG ClueBySubject - new by Subject Token: Oxide
> DEBUG CluesToConcepts - fuzzy-lookup(gas Nitrous Oxide) returned: d3.0 ~N2o nitrous oxide [N2O: Nitrous Oxide] N2O:_Nitrous_Oxide 0
> ALERT: main seems stuck for more than 300s waiting for a job delivery.
> Thread[main,5,main]  - Future java.util.concurrent.FutureTask@15a806a2 done false canc false :: AE cz.brmlab.yodaqa.analysis.question.QuestionAnalysisAE from CAS org.apache.uima.cas.impl.CASImpl@1efb1a38 (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@4ce1292a)
> 
> ALERT: pool-2-thread-1 seems stuck for more than 300s waiting for a job delivery.
> Thread[pool-2-thread-1,5,main]  - Future java.util.concurrent.FutureTask@2bf9a35a done false canc false :: AE cz.brmlab.yodaqa.analysis.question.CluesToConcepts from CAS org.apache.uima.cas.impl.CASImpl@1efb1a38 (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@4341bc48)
> 
> ALERT: main seems stuck for more than 300s waiting for a job delivery.
> Thread[main,5,main]  - Future java.util.concurrent.FutureTask@15a806a2 done false canc false :: AE cz.brmlab.yodaqa.analysis.question.QuestionAnalysisAE from CAS org.apache.uima.cas.impl.CASImpl@1efb1a38 (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@4ce1292a)
> 
> ALERT: pool-2-thread-1 seems stuck for more than 300s waiting for a job delivery.
> Thread[pool-2-thread-1,5,main]  - Future java.util.concurrent.FutureTask@2bf9a35a done false canc false :: AE cz.brmlab.yodaqa.analysis.question.CluesToConcepts from CAS org.apache.uima.cas.impl.CASImpl@1efb1a38 (CIF cz.brmlab.yodaqa.flow.asb.MultiThreadASB$CasInFlow@4341bc48)

**Comment by xteejx** [comment]
Not that I recall, am usually pretty particular with looking through log output to find the cause first. Will have a look tomorrow at its 3am here and report back.
