### ISSUE TITLE
Solr version in enwiki instructions

### ISSUE THREAD

**Issue by asher-stern** [brmson/yodaqa#72]
Hi.
I found a documentation issue in data/enwiki/README.md

The instructions are not compatible with the latest Solr release. Actually, they are compatible with a relatively old version of Solr: 4.9.1

However, the required Solr version is not specified in the README file.

Thanks.

**Comment by k0105** [comment]
Yes, as specified in the Dockerfile solr-4.6.0 is used.

**Comment by asher-stern** [comment]
Hi. Yes you are right, it is specified in the main README.
I missed it. I followed the instructions in data/enwiki/README.md, which does not specify the version.

Thanks for your answer.
