### ISSUE TITLE
http://yodaqa.felk.cvut.cz/dbp-labels2 has an error!

### ISSUE THREAD

**Issue by zerobugplz** [brmson/yodaqa#74]
http://yodaqa.felk.cvut.cz/dbp-labels2 doesn't work. It gives me nothing.

java.io.IOException: Server returned HTTP response code: 503 for URL: http://yodaqa.felk.cvut.cz/dbp-labels2/search/Obama?ver=1

**Comment by k0105** [comment]
Related to https://github.com/brmson/yodaqa/issues/73
Seems like the backend broke again.
