### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by qweqwe123** [brmson/yodaqa#9]
Hi I download yodaqa for a month ago and there all work nice but today I download the new one from you and I got this error if I run
echo | ./gradlew run    or
./gradlew run -q 

But if I run your old version it works

![error](https://cloud.githubusercontent.com/assets/5730872/8131985/8af3d7ac-111e-11e5-9f9d-694a378c4f07.png)

I hope you can help me

**Comment by pasky** [comment]
Thanks for the report.  My first idea: Could it be that you are running this in a single-CPU virtual machine? YodaQA now attempts to use multiple threads but if you have only 1 core available, that might confuse it...

**Comment by pasky** [comment]
Can you check with the latest master?  I tried to push a fix for the above.

**Comment by qweqwe123** [comment]
Hi you are right I run a single-cpu virtual machine I try it now with more core´s.
I will write about my test later

**Comment by qweqwe123** [comment]
Hi now it stuck at 80 % Building

**Comment by pasky** [comment]
Hi!  Are you sure it is stuck?  Perhaps it's just waiting for input.
Can you show the last few lines before that?

**Comment by qweqwe123** [comment]
Okay here are the picture
![error](https://cloud.githubusercontent.com/assets/5730872/8149178/df407dae-12ba-11e5-9788-ec91b96b1b08.png)

**Comment by pasky** [comment]
Intriguing! I can't reproduce that here.

If you run top in a different terminal, does that show YodaQA using the CPU?

What if you append -Dorg.slf4j.simpleLogger.log.cz.brmlab.yodaqa=debug to the gradle command line? Which lines do you see last?
